Feature/lu 10/implement topic manager
AsynchronousProgramming/async-messaging-system pull request #16
Opened 2024-12-05 00:49 UTC by fabian-romero-jalafund

## Related Ticket
- [ticket-#]()

## Description

Provide a small description of Pull Request.

## Type of Change

Put an `x` in all the boxes that apply:

- [ ] ✨ New Feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug Fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking Change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code Refactor
- [ ] ✅ Build Configuration Change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

## Pull Request Checklist

Put an `x` in all the boxes that apply:

- [ ] My commit messages are detailed.
- [ ] My code follows the code style of this project.
- [ ] No existing features have been broken without good reason.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests pass.

2024-12-05 22:26 UTC, teran-joseluis requested changes
Don't forget to make update of your branch from develop.

2024-12-05 22:26 UTC, teran-joseluis commented on app/src/main/java/salesian/university/broker/TopicManager.java
> +import java.util.*;
It'd be good if you just import those objects you use into the class and not import all.

2024-12-05 22:26 UTC, teran-joseluis commented on app/src/main/java/salesian/university/broker/TopicManager.java
> +        String topicLowerCase = topic.toLowerCase();
Dont' you think we can have a utils class for converting topic into lower case? I see you've implemented in different lines.

2024-12-05 22:26 UTC, teran-joseluis commented on app/src/main/java/salesian/university/broker/TopicManager.java
> +        return subscriptions.getOrDefault(topic.toLowerCase(), Collections.emptyList());
Why are you using `Collections.emptyList()`? Won't it return always an empty list?

2024-12-05 22:27 UTC, teran-joseluis commented
Don't forget to update also your PR title using our convention, otherwise pipelines won't let you pass.

2024-12-06 12:00 UTC, fabian-romero-jalafund commented on app/src/main/java/salesian/university/broker/TopicManager.java
> +        return subscriptions.getOrDefault(topic.toLowerCase(), Collections.emptyList());
It jus returns empty list when no topic key is found

2024-12-06 22:17 UTC, teran-joseluis requested changes
Review theses final comments and make an update of your branch from develop as result I cannot see the pipelines status.

2024-12-06 22:17 UTC, teran-joseluis commented on app/src/main/java/salesian/university/broker/TopicManager.java
> +
Please remove this extra empty line.

2024-12-06 22:17 UTC, teran-joseluis commented on app/src/test/java/salesian/university/broker/TopicManagerTest.java
> +import static org.junit.jupiter.api.Assertions.*;
Just import those functions you're using please.

2024-12-06 22:17 UTC, teran-joseluis commented on app/src/test/java/salesian/university/helpers/StringManagerTest.java
> +import static org.junit.jupiter.api.Assertions.*;
Same here please.

2024-12-08 00:01 UTC, teran-joseluis approved these changes
LGTM

2024-12-08 00:01 UTC, merged